#!/usr/bin/env bash
# script displays 'Best School' ten times and Hi at the ninth iteration

count=1
while [ $count -le 10 ]
do
  echo "Best School"
  if [ $count -eq 9 ]; then
    echo "Hi"
  fi
  ((count++))
done
