#!/usr/bin/env bash
# display 'Best School', 'bad luck' on the 4th and 'good luck' on the 8th

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done