#!/usr/bin/env bash
# display 'Best School', 'bad luck' on the 4th and 'good luck' on the 8th

count=1
while [ $count -le 20 ]
do
    case $count in
	4)
	    echo $count
	    echo "bad luck from China"
	    ;;
	9)
	    echo $count
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo $count
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $count
	    ;;
    esac
    ((count++))
done
