#!/usr/bin/env bash
# change nginx to run as nginx user


sudo sed -i '/worker_processes 4;/a\user nginx;' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2

