#!usr/bin/env bash
# refactor of configuration of nginx to be user
pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
